"""empty message.

Revision ID: 32a164187b23
Revises: 38e39c9b294e
Create Date: 2021-06-16 08:37:51.027649
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "32a164187b23"
down_revision = "38e39c9b294e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.add_column(
        "products",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("tables", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.add_column(
        "tables",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "tables",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tables", "updated_at")
    op.drop_column("tables", "created_at")
    op.drop_column("tables", "deleted")
    op.drop_column("products", "updated_at")
    op.drop_column("products", "created_at")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
