"""empty message.

Revision ID: c046f4bdcc2b
Revises: 32a164187b23
Create Date: 2021-06-16 13:36:14.326190
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c046f4bdcc2b"
down_revision = "32a164187b23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_link_product",
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
    )
    op.add_column("orders", sa.Column("table_id", sa.Integer(), nullable=True))
    try:
        op.create_foreign_key(None, "orders", "tables", ["table_id"], ["id"])
    except NotImplementedError:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_column("orders", "table_id")
    op.drop_table("order_link_product")
    # ### end Alembic commands ###
