# Generated by Django 3.2.4 on 2021-06-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('products', models.ManyToManyField(to='products.Product')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tables.table')),
            ],
            options={
                'ordering': ('position', '-created'),
                'abstract': False,
            },
        ),
    ]
