# Generated by Django 3.2.4 on 2021-06-23 07:26

from django.db import migrations

def example_products(apps, schema_editor):
    Category =apps.get_model('orders', 'Category')
    Product = apps.get_model('orders', 'Product')
    Table = apps.get_model('orders', 'Table')

    for _ in range(14):
        table = Table()
        table.save()

    drinks = Category(name='Drinks')
    drinks.save()
    snacks = Category(name='Snacks')
    snacks.save()

    for name in ['Beer', 'Wine', 'Cider']:
        product = Product(name=name)
        product.save()
        product.categories.set([drinks])

    for name in ['Crisps', 'Nuts']:
        product = Product(name=name)
        product.save()
        product.categories.set([snacks])



class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_state'),
    ]

    operations = [
        migrations.RunPython(example_products),
    ]
