# Generated by Django 3.2.4 on 2021-06-24 07:39

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210623_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[['Unprocessed', 'Unprocessed'], ['Processing', 'Processing'], ['Processed', 'Processed']], default='Unprocessed', max_length=11, protected=True, verbose_name='State'),
        ),
    ]
